version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=your_username
      - DB_PASSWORD=your_password
      - DB_NAME=your_database
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    depends_on:
      - postgres
      - redis
      - rabbitmq

  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    # container_name: redis_server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    restart: always

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight_server
    ports:
      - '5540:5540' # Adjusted to match RedisInsight default internal port
    depends_on:
      - redis
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_server
    ports:
      - '5672:5672'   # RabbitMQ messaging port
      - '15672:15672' # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    restart: always

volumes:
  postgres_data:
  redis_data:
